
["Particle Effects"]
	#Flame and smoke particles on Ashenwheat bales?
	MakeAshenBalesFlame = true
	#Gloom particles on Ossidroot crop?
	MakeOssidCropGloom = true
	#Scintillating particles on Scintillawheat crop?
	MakeScintillawheatScintillate = true
	#Gloom particles on Ossidroots, Carved Ossidroots, and Ossidroot Lanterns?
	MakeOssidLanternGloom = true
	#Scintillating particles on Scintillawheat bales?
	MakeScintillaBalesScintillate = true
	#No comment
	MakeThunderGrassSmoke = true
	#Flame particles on Ashenwheat crop?
	MakeAshenwheatFlame = true

