
[general]
	animationSpeed = 1.0
	disable_mod = false
	background_color = 1867534416
	space_modules = false
	shadow_text = true
	animations = true

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_right.lines]
		opengl_version = true
		display = false
		java_version = false
		gpu_driver = true
		memory_usage = true
		allocated_memory = false
		cpu = false
		gpu = false

[[modules_right]]
	name = "empty"
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "target"
	name_color = 43775
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		id_fluid = true
		fluid_tags = true
		block_states = true
		targeted_block = true
		block_tags = true
		id_block = true
		nothing = true
		nothing2 = true
		targeted_fluid = true
		targeted_entity = true
		fluid_states = true

[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true

	[modules_left.lines]
		minecraft = true

[[modules_left]]
	name = "help"
	name_color = 16645526
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		help = false
		pie_graph = true
		fps_tps = true

[[modules_left]]
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	name = "coords"
	name_color = 16733525
	enabled = true

	[modules_left.lines]
		chunk_coords = false
		player_coords = true
		block_coords = false
		chunk_relative_coords = true

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		light = false
		biome = true
		rotation = false
		facing = false
		local_difficulty = false
		days_played = false
		dimension = true
		highest_block = false
		highest_block_server = false
		light_server = true

[[modules_left]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		server_tick = true
		packets_sent = false
		packets_received = false

[[modules_left]]
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	color_high = 5635925
	color_med = 16777045
	name = "fps"
	enabled = true
	color_low = 16733525

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "graphics"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		shader = false
		render_distance = true
		graphics = true
		clouds = false
		biome_blend_radius = false

[[modules_left]]
	name = "entity"
	name_color = 16733525
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		entities = true
		water_creature = false
		ambient = false
		particles = true
		creature = false
		water_ambient = false
		monster = false
		misc = false

[[modules_left]]
	name = "miscleft"
	name_color = 16645526
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		misc_left = true

