#The height of generated castle, recommended value is below $WORLD_HEIGHT - 144
#Range: -99999999 ~ 99999999
castle_height = 110
#the minimum distance between castle and 0,0
#Range: 0 ~ 99999999
castle_spawn_proof = 10000
#average distance apart in chunks between spawn attempts
#Range: 0 ~ 99999999
castle_avg_dist_chunk = 500
#minimum distance apart in chunks between spawn attempts
#Range: 0 ~ 99999999
castle_min_dist_chunk = 300
#Effect Range of Laputa Core
#Range: 0 ~ 99999999
laputa_core_effect_range = 100
#Range: 0.0 ~ 1.0
yellow_key_dro_rate = 0.3
#Range: 0.0 ~ 1.0
blue_key_dro_rate = 0.1
#Range: 0.0 ~ 1.0
red_key_dro_rate = 0.02
#Player cannot place or destroy blocks in the castle
no_grief_in_castle = true

